# Generated by Django 4.1.3 on 2022-11-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.BigIntegerField()),
                ('id_evento', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sessoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=150)),
                ('lider', models.CharField(max_length=150)),
                ('tema', models.CharField(max_length=150)),
                ('formulario', models.BigIntegerField()),
                ('id_evento', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuariocd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=300)),
                ('cep', models.CharField(max_length=8)),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=500)),
                ('cidade', models.CharField(max_length=150)),
                ('bairro', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=150)),
                ('instituicao', models.CharField(max_length=150)),
                ('cmp', models.CharField(max_length=3)),
                ('categ', models.CharField(max_length=150)),
                ('cinfo', models.CharField(max_length=3)),
                ('gestor_plataforma', models.CharField(max_length=3)),
                ('autor', models.CharField(max_length=3)),
                ('avaliador', models.CharField(max_length=3)),
                ('lider', models.CharField(max_length=3)),
                ('id_usuario', models.BigIntegerField()),
                ('contato', models.BigIntegerField(null=True)),
                ('perfil', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='p1',
            new_name='c1',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='p2',
            new_name='c10',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='p3',
            new_name='c2',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='dia1',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='dia2',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='dia3',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='v1',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='v2',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='v3',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='logo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='c3',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='c4',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='c5',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='c6',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='c7',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='c8',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='c9',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='data_cadastro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nome_formulario',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='a1',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='a2',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='a3',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='autor',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='av1',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='av2',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='av3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='chave',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='data_av1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='data_av2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='data_av3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='id_evento',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='id_usuario',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='nota1',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='nota2',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='nota3',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='progresso',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='resumo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='sessao',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='titulo',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissao',
            name='trabalho',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
