# Generated by Django 4.1.1 on 2022-11-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_submissao_id_evento_alter_submissao_trabalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuariocd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=300)),
                ('cep', models.CharField(max_length=8)),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=500)),
                ('cidade', models.CharField(max_length=150)),
                ('bairro', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=150)),
                ('instituicao', models.CharField(max_length=150)),
                ('cmp', models.CharField(max_length=3)),
                ('categ', models.CharField(max_length=150)),
                ('cinfo', models.CharField(max_length=3)),
                ('id_usuario', models.BigIntegerField()),
            ],
        ),
    ]
