# Generated by Django 4.1.1 on 2022-11-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuariocd'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocd',
            name='autor',
            field=models.CharField(default='sim', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariocd',
            name='avaliador',
            field=models.CharField(default='sim', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariocd',
            name='gestor_plataforma',
            field=models.CharField(default='sim', max_length=3),
            preserve_default=False,
        ),
    ]
