# Generated by Django 4.1.1 on 2022-11-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuariocd_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='dia1',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='dia2',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='dia3',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(default='mg', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='logo',
            field=models.FileField(default='logoeventopadrao', upload_to=''),
            preserve_default=False,
        ),
    ]
