# Generated by Django 4.1.1 on 2022-11-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_evento_dia1_remove_evento_dia2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=150)),
                ('lider', models.CharField(max_length=150)),
                ('tema', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='usuariocd',
            name='lider',
            field=models.CharField(default='sim', max_length=3),
            preserve_default=False,
        ),
    ]
