# Generated by Django 4.1.1 on 2022-11-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sessoes_usuariocd_lider'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessoes',
            name='id_evento',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
