# Generated by Django 4.1.1 on 2022-11-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_inscritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='av1',
            field=models.CharField(default='aguardando', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='av2',
            field=models.CharField(default='aguardando', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='av3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='data_av1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='data_av2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='data_av3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='id_usuario',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='sessao',
            field=models.BigIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='status',
            field=models.CharField(default='aguardando', max_length=30),
            preserve_default=False,
        ),
    ]
