# Generated by Django 4.1.1 on 2022-11-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_submissao_av1_submissao_av2_submissao_av3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('av1', models.CharField(max_length=150)),
                ('av2', models.CharField(max_length=150)),
                ('av3', models.CharField(max_length=150)),
                ('id_sessao', models.BigIntegerField()),
            ],
        ),
    ]
