# Generated by Django 4.1.1 on 2022-11-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_p1_formulario_c1_rename_p2_formulario_c10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessoes',
            name='formulario',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
