# Generated by Django 4.1.1 on 2022-11-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sessoes_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='chave',
            field=models.TextField(default='trabalho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='resumo',
            field=models.TextField(default='Trabalho propondo melhorias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='titulo',
            field=models.CharField(default='Agora Tem Titulo', max_length=150),
            preserve_default=False,
        ),
    ]
