# Generated by Django 4.1.1 on 2022-11-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_submissao_chave_submissao_resumo_submissao_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='autor',
            field=models.CharField(default='Leonardo Bastos Freitas', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='nota1',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='nota2',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='nota3',
            field=models.BigIntegerField(null=True),
        ),
    ]
