# Generated by Django 4.1.1 on 2022-11-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_submissao_autor_submissao_nota1_submissao_nota2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='a1',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='a2',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='a3',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='progresso',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
