# Generated by Django 4.1.1 on 2022-12-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_submissao_a1_submissao_a2_submissao_a3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cpfteste',
        ),
        migrations.RenameField(
            model_name='inscritos',
            old_name='id_evento',
            new_name='evento',
        ),
        migrations.AddField(
            model_name='inscritos',
            name='cidade',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscritos',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inscritos',
            name='doc',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscritos',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscritos',
            name='id_user',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscritos',
            name='instituicao',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscritos',
            name='modalidade',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscritos',
            name='pagamento',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='cpf',
            field=models.CharField(max_length=15),
        ),
    ]
