# Generated by Django 4.1.1 on 2022-12-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_autores'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores',
            name='id_trabalho',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
