# Generated by Django 4.1.1 on 2022-12-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_autores_id_trabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autores',
            name='instituicao',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
