# Generated by Django 4.1.1 on 2022-12-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_autores_email_autores_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
