# Generated by Django 4.1.1 on 2022-12-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_salvarform'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='ccriterios',
            field=models.BigIntegerField(default=10),
            preserve_default=False,
        ),
    ]
