# Generated by Django 4.1.1 on 2022-12-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_formulario_ccriterios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='id_evento',
            field=models.CharField(max_length=600),
        ),
    ]
